# Generated by Django 5.2.8 on 2026-03-17 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bika', '0007_productalert_details_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruitbatch',
            options={'verbose_name': 'Mushroom Batch', 'verbose_name_plural': 'Mushroom Batches'},
        ),
        migrations.AlterModelOptions(
            name='fruitqualityreading',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Mushroom Quality Reading', 'verbose_name_plural': 'Mushroom Quality Readings'},
        ),
        migrations.AlterModelOptions(
            name='fruittype',
            options={'verbose_name': 'Mushroom Type', 'verbose_name_plural': 'Mushroom Types'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='mushroom_name',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='fruitbatch',
            name='batch_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mushroom Batch ID'),
        ),
        migrations.AlterField(
            model_name='fruitbatch',
            name='fruit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bika.fruittype', verbose_name='Mushroom Type'),
        ),
        migrations.AlterField(
            model_name='fruitbatch',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Quantity in kg or units'),
        ),
        migrations.AlterField(
            model_name='fruitqualityreading',
            name='actual_class',
            field=models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Rotten', 'Rotten')], max_length=20, verbose_name='Actual Quality'),
        ),
        migrations.AlterField(
            model_name='fruitqualityreading',
            name='co2_level',
            field=models.IntegerField(help_text='CO2 in ppm'),
        ),
        migrations.AlterField(
            model_name='fruitqualityreading',
            name='firmness',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Firmness index', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fruitqualityreading',
            name='fruit_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_readings', to='bika.fruitbatch', verbose_name='Mushroom Batch'),
        ),
        migrations.AlterField(
            model_name='fruitqualityreading',
            name='humidity',
            field=models.DecimalField(decimal_places=2, help_text='Humidity %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fruitqualityreading',
            name='predicted_class',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Rotten', 'Rotten')], max_length=20, verbose_name='AI Predicted Quality'),
        ),
        migrations.AlterField(
            model_name='fruitqualityreading',
            name='temperature',
            field=models.DecimalField(decimal_places=2, help_text='Temp in °C', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='chilling_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='ethylene_sensitive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Mushroom Type'),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='optimal_co2_max',
            field=models.IntegerField(default=800, help_text='Max CO2 (ppm)'),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='optimal_humidity_max',
            field=models.DecimalField(decimal_places=2, default=95.0, help_text='Max Humidity (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='optimal_humidity_min',
            field=models.DecimalField(decimal_places=2, default=90.0, help_text='Min Humidity (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='optimal_light_max',
            field=models.IntegerField(default=50, help_text='Max Light (lux)'),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='optimal_temp_max',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Max Temp (°C)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='optimal_temp_min',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Min Temp (°C)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fruittype',
            name='shelf_life_days',
            field=models.IntegerField(default=5, help_text='Average shelf life in days'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('RWF', 'Rwandan Franc'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='RWF', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='bika.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight in kilograms'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='bika.product'),
        ),
    ]
